Nick House
CS-4200 - Final
14 Dec 2020

In [1]:
import numpy as np
import pandas as pd

# -------------------- Part 1 --------------------------

NSCORES = 5
NSTUDENTS = 10

#Implement a class called Student
class Student:

    #Include code in the class definition to keep track of how many Student objects are created.
    StudentObjects = 0
    score = np.double(0)

    def __init__(self, rand):
        self.score = self.f(rand)
        Student.StudentObjects += 1
    
    #Return Double of X
    def f(self, x):
        return np.double(x)
    
    #Return Score
    def get(self):
        return self.score 


#Create list of students and perform computations

stulist = np.frompyfunc(Student, 1, 1)(np.random.randint(1,NSCORES+1, size = np.random.randint(1,NSTUDENTS + 1)))

print("Number of Student Objects Created: " + str(Student.StudentObjects))
   
print("Average: " + str(np.mean([i.score for i in stulist]) ))

Number of Student Objects Created: 6
Average: 2.6666666666666665


In [2]:
# -------------------- Part 2 --------------------------
# Output requirements for part 2 a-f 

#a.)
x = np.random.uniform(0,1,(3,4))
print("a.) \n" +str(x) + "\n")

#b.)
sqr = np.random.uniform(0,1,(3,1))
z = x + np.dot(sqr[:,0], sqr[:,0])
print("b.) \n" +str(z) + "\n")

#c.)
p = z/np.max(z, axis = 0)
print("c.) \n" + str(p) + "\n")

#d.)
p = np.where(p <.5, .3, p)
print("d.) \n" + str(p) + "\n")

#e.)
print("e.) \n" + str(np.where(np.argmax(p.sum(axis=0)) == np.argmin(p.sum(axis = 1)), 'True', 'False')) + "\n")

#f.)
print("f.) \n" + str(np.flip(np.min(p, axis = 0)))+ "\n")



a.) 
[[0.70462557 0.95334113 0.59977891 0.67134607]
 [0.99469458 0.77982033 0.40908717 0.54429336]
 [0.39889315 0.65430839 0.59949633 0.05540033]]

b.) 
[[2.6074221  2.85613766 2.50257543 2.5741426 ]
 [2.89749111 2.68261686 2.3118837  2.44708989]
 [2.30168967 2.55710492 2.50229286 1.95819686]]

c.) 
[[0.89988959 1.         1.         1.        ]
 [1.         0.93924635 0.9238018  0.95064271]
 [0.79437333 0.8953017  0.99988709 0.7607181 ]]

d.) 
[[0.89988959 1.         1.         1.        ]
 [1.         0.93924635 0.9238018  0.95064271]
 [0.79437333 0.8953017  0.99988709 0.7607181 ]]

e.) 
True

f.) 
[0.7607181  0.9238018  0.8953017  0.79437333]

